apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flashorca-ally-devnet-ingress
  namespace: nexus-ai
  annotations:
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/upgrade-websocket: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-burst: "40"
    nginx.ingress.kubernetes.io/limit-req-status-code: "429"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ally-devnet.flashorca.com
      secretName: flashorca-ally-devnet-tls
  rules:
    - host: ally-devnet.flashorca.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flashorca-ally-devnet-service
                port:
                  number: 80
